# Generated by Django 2.2 on 2020-12-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweet_petite_app', '0002_goods'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='picture',
            field=models.ImageField(default='cookie.jpg', upload_to=None),
            preserve_default=False,
        ),
    ]
