# Generated by Django 2.2 on 2020-12-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweet_petite_app', '0011_auto_20201216_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='description',
            field=models.CharField(default='Delicious Cookies', max_length=255),
            preserve_default=False,
        ),
    ]
