# Generated by Django 2.2 on 2020-12-21 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sweet_petite_app', '0016_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='sweet_petite_app.Goods'),
            preserve_default=False,
        ),
    ]
