# Generated by Django 2.2 on 2020-12-21 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweet_petite_app', '0018_remove_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantity_ordered',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.CharField(max_length=255),
        ),
    ]
