# Generated by Django 2.2 on 2020-12-21 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweet_petite_app', '0019_auto_20201221_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantity_ordered',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
