# Generated by Django 2.2 on 2020-12-21 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweet_petite_app', '0022_auto_20201221_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='goods',
            field=models.CharField(max_length=255),
        ),
    ]
