# Generated by Django 2.2 on 2020-12-21 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sweet_petite_app', '0023_auto_20201221_2139'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
