# Generated by Django 2.2 on 2020-12-21 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sweet_petite_app', '0025_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
