# Generated by Django 2.2 on 2021-01-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweet_petite_app', '0028_auto_20210104_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='best_seller',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
