# Generated by Django 2.2 on 2021-01-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweet_petite_app', '0030_auto_20210105_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='best_seller',
            field=models.BooleanField(default=True),
        ),
    ]
